// core/fundCache.ts
// Mirrors priceCache.ts, but for mutual fund NAVPU. Separate module because
// it's a different feed with a different schema (navpu instead of
// price+yieldPct, plus roiYoyPct/roiYtdPct/category/bank that stocks don't
// have) generated by a different upstream scraper (UITF NAVPU pages, not
// PSE/dividends.ph) - see public/data/funds.json, sibling file to prices.json
// in the same bucket-manager-web project.

import { normalizeGithubUrl } from './priceCache';
import { PriceLookup } from './bucketLogic';

export interface FundEntry {
  navpu: number;
  roiYoyPct: number | null;
  roiYtdPct: number | null;
  category: string;
  bank: string;
  /** Some funds' NAV cycle lags a day behind the rest of the batch - when
   *  set, this is the date THIS fund's navpu actually reflects, distinct
   *  from the batch-wide `generatedAt` on the cache as a whole. */
  staleAsOf: string | null;
  source: string;
}

export interface FundCache {
  generatedAt: string;
  funds: Record<string, FundEntry>;
  errors?: Record<string, string>;
  backupCheckedAt?: string;
}

// Same repo as DEFAULT_PRICE_CACHE_URL (priceCache.ts), sibling file under
// public/data/ - see that constant's comment for why this must resolve to
// the raw content URL, not the github.com file-viewer page.
export const DEFAULT_FUND_CACHE_URL =
  'https://github.com/blueprinttradingfx-cpu/bucket-manager-web/blob/master/public/data/funds.json';

let memoryCache: FundCache | null = null;
let memoryCacheAt = 0;
const MEMORY_TTL_MS = 60 * 60 * 1000; // NAVPU updates at most once/day, same reasoning as priceCache's TTL

export async function fetchFundCache(
  url: string = DEFAULT_FUND_CACHE_URL,
  opts: { force?: boolean } = {}
): Promise<FundCache> {
  if (!opts.force && memoryCache && Date.now() - memoryCacheAt < MEMORY_TTL_MS) {
    return memoryCache;
  }
  console.log('[fundCache] fetching', url);
  const fetchUrl = normalizeGithubUrl(url);
  const res = await fetch(fetchUrl);
  if (!res.ok) {
    throw new Error(`Failed to fetch fund cache: HTTP ${res.status} from ${fetchUrl}`);
  }
  const data = (await res.json()) as FundCache;
  console.log('[fundCache] loaded', Object.keys(data.funds ?? {}).length, 'funds, generated', data.generatedAt);
  memoryCache = data;
  memoryCacheAt = Date.now();
  return data;
}

export function getFundPrice(cache: FundCache | null, ticker: string): FundEntry | null {
  return cache?.funds?.[ticker] ?? null;
}

export function isFundCacheStale(cache: FundCache, maxAgeHours = 48): boolean {
  const ageMs = Date.now() - new Date(cache.generatedAt).getTime();
  return ageMs > maxAgeHours * 60 * 60 * 1000;
}

/** Adapts fund NAVPU entries into the same shape applyPricesToAggregated /
 *  applyPricesToPositions already expect for stocks (PriceLookup), so the
 *  existing valuation math in bucketLogic.ts can value funds too without any
 *  changes there - it just sees more entries in the lookup it's handed.
 *  yieldPct is always null: funds don't carry a per-share dividend yield the
 *  way stocks do.
 *
 *  Matching is by ticker string, same convention priceCache already uses for
 *  stocks: whatever's in a fund holding's `ticker` (the DragonFi statement's
 *  Stock column) must match a key in funds.json exactly (e.g. "BPIEF1"). A
 *  fund whose ticker doesn't appear here just falls through to the existing
 *  "no live price" handling in bucketLogic - same graceful degradation as an
 *  unmatched stock ticker, not a crash. */
export function fundCacheToPriceLookup(cache: FundCache | null): PriceLookup {
  const out: PriceLookup = {};
  if (!cache) return out;
  for (const [ticker, entry] of Object.entries(cache.funds)) {
    out[ticker] = { price: entry.navpu, yieldPct: null };
  }
  return out;
}
