// core/priceCache.ts
// Fetches the static price/yield JSON produced by the GitHub Actions
// pipeline (scripts/generate_price_cache.py, committed to
// public/data/prices.json - see the separate bucket-manager-web project).
// One implementation for ALL platforms - no .native/.web split needed here,
// because raw.githubusercontent.com serves `Access-Control-Allow-Origin: *`
// (verified directly: `curl -sI` against a real file on that host returned
// exactly that header), so the browser's CORS restriction that forced a
// platform split for xlsx import simply doesn't apply to this fetch.

export interface PriceEntry {
  price: number;
  yieldPct: number | null; // null for companies that don't pay dividends - a valid state, not missing data
  source?: 'dragonfi' | 'dividends.ph' | 'filgit'; // which scraper produced this entry - see price-scraper/README.md
}

export interface PriceCache {
  generatedAt: string;
  tickers: Record<string, PriceEntry>;
  errors?: Record<string, string>;
  backupCheckedAt?: string; // set by the filgit backup workflow each time it runs, even if it found no gaps to fill
}

// Points at the user's bucket-manager-expo repo, generated by the
// refresh-prices.yml GitHub Actions workflow. If you fork/move this repo,
// update this to your own raw.githubusercontent.com URL (see comment
// above normalizeGithubUrl for why it must be the raw form, not a
// github.com/.../blob/... link).
export const DEFAULT_PRICE_CACHE_URL =
  'https://github.com/blueprinttradingfx-cpu/bucket-manager-web/blob/master/public/data/prices.json';

// It's an easy mistake to paste the URL straight from the GitHub file
// viewer (github.com/.../blob/...) instead of the raw content URL - the
// former is an HTML page and gets blocked by CORS when fetched from the
// browser (no Access-Control-Allow-Origin header), which is exactly what
// that looks like when it happens: "Failed to fetch" with a CORS console
// error, not a 404. Auto-correct it rather than requiring the exact form.
export function normalizeGithubUrl(url: string): string {
  const blobMatch = url.match(/^https:\/\/github\.com\/([^/]+)\/([^/]+)\/blob\/([^/]+)\/(.+)$/);
  if (blobMatch) {
    const [, owner, repo, branch, path] = blobMatch;
    const fixed = `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/${path}`;
    console.log('[priceCache] rewrote github.com blob URL to raw content URL:', fixed);
    return fixed;
  }
  return url;
}

let memoryCache: PriceCache | null = null;
let memoryCacheAt = 0;
const MEMORY_TTL_MS = 60 * 60 * 1000; // 1 hour - avoid refetching on every screen mount; the underlying data itself only refreshes once/day anyway

export async function fetchPriceCache(
  url: string = DEFAULT_PRICE_CACHE_URL,
  opts: { force?: boolean } = {}
): Promise<PriceCache> {
  if (!opts.force && memoryCache && Date.now() - memoryCacheAt < MEMORY_TTL_MS) {
    return memoryCache;
  }
  console.log('[priceCache] fetching', url);
  const fetchUrl = normalizeGithubUrl(url);
  const res = await fetch(fetchUrl);
  if (!res.ok) {
    throw new Error(`Failed to fetch price cache: HTTP ${res.status} from ${fetchUrl}`);
  }
  const data = (await res.json()) as PriceCache;
  console.log('[priceCache] loaded', Object.keys(data.tickers ?? {}).length, 'tickers, generated', data.generatedAt);
  memoryCache = data;
  memoryCacheAt = Date.now();
  return data;
}

export function getPrice(cache: PriceCache | null, ticker: string): PriceEntry | null {
  return cache?.tickers?.[ticker] ?? null;
}

export function isStale(cache: PriceCache, maxAgeHours = 48): boolean {
  const ageMs = Date.now() - new Date(cache.generatedAt).getTime();
  return ageMs > maxAgeHours * 60 * 60 * 1000;
}
