// core/priceCache.ts
// Fetches the static price/yield JSON produced by the GitHub Actions
// pipeline (scripts/generate_price_cache.py, committed to
// public/data/prices.json - see the separate bucket-manager-web project).
// One implementation for ALL platforms - no .native/.web split needed here.
// Data is served through a Cloudflare Worker proxy (ani-data-proxy) rather
// than fetched directly from raw.githubusercontent.com - the Worker holds a
// read-only GitHub PAT server-side and re-serves the JSON under generic
// route names, so the app's network traffic never reveals the source repo
// or GitHub username. The Worker also replicates the
// `Access-Control-Allow-Origin: *` header raw.githubusercontent.com used to
// provide for free, so the web build's CORS behavior is unchanged.
//
// TODO: once a custom domain is attached to the Worker (see setup notes),
// swap this for the custom domain - it's a one-line change since every
// fetch in this codebase goes through DATA_PROXY_BASE_URL.
export const DATA_PROXY_BASE_URL = 'https://ani-data-proxy.blueprinttradingfx.workers.dev';

export interface PriceEntry {
  price: number;
  yieldPct: number | null; // null for companies that don't pay dividends - a valid state, not missing data
  source?: 'dragonfi' | 'dividends.ph' | 'filgit'; // which scraper produced this entry - see price-scraper/README.md
}

export interface PriceCache {
  generatedAt: string;
  tickers: Record<string, PriceEntry>;
  errors?: Record<string, string>;
  backupCheckedAt?: string; // set by the filgit backup workflow each time it runs, even if it found no gaps to fill
}

// Generated by the refresh-prices-filgit.yml / refresh-prices-dragonfi.yml
// GitHub Actions workflows in bucket-manager-web, served through the Worker
// proxy - see DATA_PROXY_BASE_URL above.
export const DEFAULT_PRICE_CACHE_URL = `${DATA_PROXY_BASE_URL}/v1/prices`;

let memoryCache: PriceCache | null = null;
let memoryCacheAt = 0;
const MEMORY_TTL_MS = 60 * 60 * 1000; // 1 hour - avoid refetching on every screen mount; the underlying data itself only refreshes once/day anyway

export async function fetchPriceCache(
  url: string = DEFAULT_PRICE_CACHE_URL,
  opts: { force?: boolean } = {}
): Promise<PriceCache> {
  if (!opts.force && memoryCache && Date.now() - memoryCacheAt < MEMORY_TTL_MS) {
    return memoryCache;
  }
  console.log('[priceCache] fetching', url);
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch price cache: HTTP ${res.status} from ${url}`);
  }
  const data = (await res.json()) as PriceCache;
  console.log('[priceCache] loaded', Object.keys(data.tickers ?? {}).length, 'tickers, generated', data.generatedAt);
  memoryCache = data;
  memoryCacheAt = Date.now();
  return data;
}

export function getPrice(cache: PriceCache | null, ticker: string): PriceEntry | null {
  return cache?.tickers?.[ticker] ?? null;
}

export function isStale(cache: PriceCache, maxAgeHours = 48): boolean {
  const ageMs = Date.now() - new Date(cache.generatedAt).getTime();
  return ageMs > maxAgeHours * 60 * 60 * 1000;
}
